{% set name = "compact-json" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/compact-json-{{ version }}.tar.gz
  sha256: 099a0f1da2b35c9e4cccf1f2e59488c95983655855de9700017fcfdd2414a4de

build:
  entry_points:
    - compact-json=compact_json._compact_json:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - compact_json
  commands:
    - pip check
    - compact-json --help
  requires:
    - pip

about:
  home: https://github.com/masaccio/compact-json
  summary: A JSON formatter that produces compact but human-readable
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - thewchan
